version: "3"

tasks:
  app_migrations:
    aliases:
      - gen
    decs: "Migrations"
    cmds: 
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations

  test_migrations:
    aliases:
      - gen
    decs: "Migrations for tests"
    cmds: 
      - go run ./cmd/migrator/main.go --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test

  run_app:
    aliases:
      - run
    desc: "Running application"
    cmds: 
     - go run cmd/sso/main.go --config=./config/local.yaml